name: Update References

on:
  push:

jobs:
  input-reference:
    runs-on: ubuntu-latest

    name: Update Input Reference
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up CPython Version 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install Requirements
        shell: bash
        run: |
          pip install -r _update_ref/requirements.txt
    
      - name: Run Updater
        run: |
          python -m _update_ref
    
      - name: Push Changes
        continue-on-error: true
        run: |
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit --author="cibere <71997063+cibere@users.noreply.github.com>" -m "Auto update input reference"
          git push